language: node_js
node_js:
- node
before_script:
- npm install -g --silent @angular/cli
script:
- ng build --prod
before_deploy:
    - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
deploy:
  provider: releases
  user: $G_USER
  password: $G_PASS
  file: $TRAVIS_BUILD_DIR+"/**/*"
  skip_cleanup: true
  keep-history: true
  repo: https://github.com/jr33d/jr33d.github.io
  target-branch: master
  on:
    tags: true
    branch: master
