language: node_js
node_js:
- node
before_script:
- npm install -g --silent @angular/cli
script:
- ng build --prod
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  repo: https://github.com/jr33d/jr33d.github.io
  target-branch: master
  on:
    branch: master
