language: node_js
node_js:
- node
before_script:
- npm install -g --silent @angular/cli
script:
- ng build --prod
deploy:
    on:
        branch: master
    provider: pages
    skip_cleanup: true
    keep-history: true
    local-dir: "/dist/jr33d-io"
    github_token:
        secure: d4f94aa61241d92a01a2591b41638db5f360fb2d
    repo: jr33d/jr33d.github.io
    target-branch: master
notifications:
    email:
        on_success: never
        on_failure: change

